const remoteProjectDefaults = {
  launchMode: 'external',
  status: 'unknown',
  updatedAt: null,
  projectType: 'web-app',
}

export const APP_MANIFEST = [
  {
    ...remoteProjectDefaults,
    id: 'tools',
    name: 'Tools',
    icon: '🛠️',
    color: '#FF9500',
    url: 'https://tools.gmlhub.top',
    healthUrl: 'https://tools.gmlhub.top',
    domain: 'tools.gmlhub.top',
    repoUrl: 'https://github.com/kaliluying/MyTools',
    description: 'Vue 3 + TS + Django DRF 工具集',
    stack: ['Vue 3', 'TypeScript', 'Django DRF', 'Naive UI'],
    content: '面向日常开发与媒体处理的在线工具集合。',
  },
  {
    ...remoteProjectDefaults,
    id: 'wiki',
    name: '知识库',
    icon: '📚',
    color: '#007AFF',
    url: 'https://wiki.gmlhub.top',
    healthUrl: 'https://wiki.gmlhub.top',
    domain: 'wiki.gmlhub.top',
    repoUrl: 'https://github.com/kaliluying/knowledge-ai',
    description: 'Vue 3 + Django + PostgreSQL 知识库',
    stack: ['Vue 3', 'Django 5.2', 'PostgreSQL 17', 'TipTap', 'D3.js'],
    content: '把文档、结构化知识与 AI 辅助检索组织在一起的知识工作台。',
  },
  {
    ...remoteProjectDefaults,
    id: 'vault',
    name: '密码箱',
    icon: '🔐',
    color: '#34C759',
    url: 'https://vault.gmlhub.top',
    healthUrl: 'https://vault.gmlhub.top',
    domain: 'vault.gmlhub.top',
    repoUrl: 'https://github.com/kaliluying/vault',
    description: 'FastAPI + PostgreSQL + Redis 密码管理',
    stack: ['FastAPI', 'PostgreSQL', 'Redis', 'Jinja2', 'cryptography'],
    content: '以本地化、可控的方式管理敏感凭据与访问信息。',
  },
  {
    ...remoteProjectDefaults,
    id: 'blog',
    name: '博客',
    icon: '📝',
    color: '#AF52DE',
    url: 'https://blog.gmlhub.top',
    healthUrl: 'https://blog.gmlhub.top',
    domain: 'blog.gmlhub.top',
    repoUrl: 'https://github.com/kaliluying/blog-ai',
    description: 'Vue 3 + FastAPI + PostgreSQL AI 博客',
    stack: ['Vue 3', 'FastAPI', 'SQLAlchemy 2.0', 'Alembic', 'Pytest'],
    content: '记录 AI 产品、全栈工程实践与持续交付过程中的真实经验。',
  },
  {
    ...remoteProjectDefaults,
    id: 'github',
    name: 'GitHub',
    icon: '🐙',
    color: '#24292f',
    url: 'https://github.com/kaliluying',
    healthUrl: 'https://github.com/kaliluying',
    domain: 'github.com',
    repoUrl: 'https://github.com/kaliluying',
    description: '代码仓库主页',
    content: '公开项目、实验性工具与技术积累的统一入口。',
  },
  {
    ...remoteProjectDefaults,
    id: 'clipboard-history',
    name: '剪贴板',
    icon: '📋',
    color: '#5856D6',
    url: 'https://github.com/kaliluying/clipboard-history',
    healthUrl: 'https://github.com/kaliluying/clipboard-history',
    domain: 'github.com',
    repoUrl: 'https://github.com/kaliluying/clipboard-history',
    description: 'Tauri 剪贴板历史记录管理工具',
    stack: ['Tauri', 'Rust', 'Vue'],
    content: '将常用复制内容沉淀为可搜索、可复用的桌面效率工具。',
  },
  {
    ...remoteProjectDefaults,
    id: 'bilibili',
    name: '哔哩哔哩',
    icon: '📺',
    color: '#00A1D6',
    url: 'https://space.bilibili.com/671157361',
    healthUrl: 'https://space.bilibili.com/671157361',
    domain: 'space.bilibili.com',
    description: 'B站空间主页',
    content: '视频与公开内容发布渠道。',
  },
  {
    id: 'terminal',
    name: '终端',
    icon: '>_',
    color: '#000000',
    url: null,
    domain: 'terminal.local',
    launchMode: 'internal',
    pluginId: 'terminal',
    status: 'local',
    updatedAt: null,
    description: '命令行终端',
  },
  {
    id: 'settings',
    name: '设置',
    icon: '⚙️',
    color: '#8E8E93',
    url: null,
    domain: 'settings.local',
    launchMode: 'internal',
    pluginId: 'settings',
    status: 'local',
    updatedAt: null,
    description: '系统设置',
  },
  {
    id: 'profile',
    name: '关于我',
    icon: '👤',
    color: '#5AC8FA',
    url: null,
    domain: 'profile.local',
    launchMode: 'internal',
    pluginId: 'personal-info',
    status: 'local',
    updatedAt: null,
    description: '开发者：GML｜专注 AI 全栈产品与效率工具落地',
    detailTitle: '个人简介',
    details: [
      '独立开发者，持续交付 Vue + Python 技术栈的线上产品。',
      '近期项目覆盖工具集、知识库、密码管理与 AI 博客四条产品线。',
      '偏好把复杂流程拆成可复用、可维护、可持续迭代的工程模块。',
    ],
    quickFacts: [
      { label: '方向', value: 'AI 全栈 / 工具产品' },
      { label: '地点', value: '中国 · 远程协作' },
      { label: '主力后端', value: 'FastAPI / Django REST Framework' },
      { label: '状态', value: '可接合作 / 技术交流' },
    ],
    actions: [
      { id: 'profile-blog', label: '打开博客', type: 'link', value: 'https://blog.gmlhub.top' },
      { id: 'profile-github', label: '打开 GitHub', type: 'link', value: 'https://github.com/kaliluying' },
    ],
  },
  {
    id: 'contact',
    name: '联系方式',
    icon: '📮',
    color: '#FF2D55',
    url: null,
    domain: 'contact.local',
    launchMode: 'internal',
    pluginId: 'personal-info',
    status: 'local',
    updatedAt: null,
    description: '邮箱：kaliluying@gmail.com｜GitHub：github.com/kaliluying',
    detailTitle: '联系渠道',
    details: [
      '欢迎合作邀约、技术交流与问题反馈。',
      '优先邮件联系，通常会在 24 小时内回复。',
    ],
    quickFacts: [
      { label: '邮箱', value: 'kaliluying@gmail.com' },
      { label: 'GitHub', value: 'github.com/kaliluying' },
      { label: 'Bilibili', value: 'space.bilibili.com/671157361' },
      { label: '沟通偏好', value: '邮件 > GitHub Issue / 私信' },
    ],
    actions: [
      { id: 'contact-email-copy', label: '复制邮箱', type: 'copy', value: 'kaliluying@gmail.com' },
      { id: 'contact-email-open', label: '写邮件', type: 'link', value: 'mailto:kaliluying@gmail.com' },
      { id: 'contact-github-copy', label: '复制 GitHub', type: 'copy', value: 'https://github.com/kaliluying' },
      { id: 'contact-github-open', label: '打开 GitHub', type: 'link', value: 'https://github.com/kaliluying' },
      { id: 'contact-bilibili-open', label: '打开 Bilibili', type: 'link', value: 'https://space.bilibili.com/671157361' },
    ],
  },
  {
    id: 'stack',
    name: '技术栈',
    icon: '🧩',
    color: '#30D158',
    url: null,
    domain: 'stack.local',
    launchMode: 'internal',
    pluginId: 'personal-info',
    status: 'local',
    updatedAt: null,
    description: 'Vue 3 + TypeScript / FastAPI / Django / PostgreSQL / Redis',
    detailTitle: '技术与项目证据',
    details: [
      '核心交付栈：Vue 3 + TypeScript + Vite，后端以 FastAPI 与 Django 双栈并行。',
      '数据层以 PostgreSQL 为主，按场景使用 Redis 会话与异步访问能力。',
      '在多项目中持续实践 Pinia、Vue Router、DRF、SQLAlchemy、Alembic 与 Pytest。',
    ],
    quickFacts: [
      { label: '前端', value: 'Vue 3 / TypeScript / Vite / Pinia / Vue Router' },
      { label: '后端', value: 'FastAPI / Django 5.2 / DRF / SQLAlchemy 2.0' },
      { label: '数据与安全', value: 'PostgreSQL / Redis / asyncpg / cryptography' },
      { label: '质量保障', value: 'Vitest / Pytest / Alembic / Docker Compose' },
    ],
    evidence: [
      { id: 'ev-tools', name: 'MyTools / Tools', meta: 'Vue 3 + TS + Django DRF + Naive UI + FFmpeg', url: 'https://github.com/kaliluying/MyTools' },
      { id: 'ev-wiki', name: 'knowledge-ai / 知识库', meta: 'Vue 3 + Django 5.2 + PostgreSQL 17 + TipTap + D3.js', url: 'https://github.com/kaliluying/knowledge-ai' },
      { id: 'ev-vault', name: 'vault / 密码箱', meta: 'FastAPI + PostgreSQL + Redis + Jinja2 + cryptography', url: 'https://github.com/kaliluying/vault' },
      { id: 'ev-blog', name: 'blog-ai / 博客', meta: 'Vue 3 + FastAPI + SQLAlchemy 2.0 + Alembic + Pytest', url: 'https://github.com/kaliluying/blog-ai' },
    ],
    actions: [
      { id: 'stack-tools', label: '打开 Tools', type: 'link', value: 'https://tools.gmlhub.top' },
      { id: 'stack-wiki', label: '打开知识库', type: 'link', value: 'https://wiki.gmlhub.top' },
      { id: 'stack-vault', label: '打开密码箱', type: 'link', value: 'https://vault.gmlhub.top' },
      { id: 'stack-blog', label: '打开博客', type: 'link', value: 'https://blog.gmlhub.top' },
      { id: 'stack-github', label: '查看 GitHub', type: 'link', value: 'https://github.com/kaliluying' },
    ],
  },
]

export const getInitialApps = () => APP_MANIFEST.map(app => ({
  ...app,
  status: app.launchMode === 'internal' ? 'local' : 'unknown',
  updatedAt: app.launchMode === 'internal' ? null : null,
}))
